export { default as Home } from './Home/Home'
export { default as Contact } from './Contact/Contact'
export { default as Login } from './auth/Login/Login'
export { default as Register } from './auth/Register/Register'
export { default as ResetPassword } from './auth/ResetPassword/ResetPassword'